"use client";

import { Bell, Building2, Heart, Home, Map, Menu, MessageCircle, Search, ShieldCheck, Truck, UserRound } from "lucide-react";
import { Brand } from "@/components/brand";
import type { AppSection } from "@/types/marketplace";
import { cn } from "@/lib/utils";

const mobileNav: { id: AppSection; label: string; icon: typeof Home }[] = [
  { id: "home", label: "Home", icon: Home }, { id: "search", label: "Search", icon: Search }, { id: "map", label: "Map", icon: Map }, { id: "favorites", label: "Saved", icon: Heart }, { id: "messages", label: "Messages", icon: MessageCircle }, { id: "profile", label: "Profile", icon: UserRound },
];

export function AppShell({ active, onNavigate, children }: { active: AppSection; onNavigate: (section: AppSection) => void; children: React.ReactNode }) {
  return <div className="min-h-screen bg-[#f8f8f3] text-[#173f3b]"><header className="sticky top-0 z-40 border-b border-[#dfe8e4]/80 bg-[#f8f8f3]/90 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-4 sm:px-6"><button onClick={() => onNavigate("home")}><Brand /></button><nav className="hidden items-center gap-1 lg:flex">{[{ id: "home", label: "Find a home" }, { id: "movers", label: "Movers" }, { id: "provider", label: "List a property" }].map((item) => <button key={item.id} onClick={() => onNavigate(item.id as AppSection)} className={cn("rounded-full px-4 py-2 text-sm font-bold transition", active === item.id ? "bg-[#e6f2ee] text-[#0f766e]" : "text-[#526b65] hover:bg-white")}>{item.label}</button>)}</nav><div className="flex items-center gap-2"><button className="hidden h-10 w-10 place-items-center rounded-full bg-white text-[#526b65] shadow-sm sm:grid"><Bell className="h-5 w-5" /></button><button onClick={() => onNavigate("profile")} className="flex items-center gap-2 rounded-full bg-[#123b38] px-3 py-2 text-xs font-bold text-white"><UserRound className="h-4 w-4" /><span className="hidden sm:inline">My HomeSpot</span></button><button className="grid h-10 w-10 place-items-center rounded-full lg:hidden"><Menu className="h-5 w-5" /></button></div></div></header><main className="mx-auto max-w-7xl px-4 pb-28 pt-5 sm:px-6 sm:pt-7 lg:pb-12">{children}</main><nav className="fixed inset-x-0 bottom-0 z-40 border-t border-[#dce6e2] bg-white/95 px-2 pb-[max(0.5rem,env(safe-area-inset-bottom))] pt-2 shadow-[0_-10px_35px_-24px_rgba(18,59,56,0.35)] backdrop-blur-xl lg:hidden"><div className="mx-auto grid max-w-lg grid-cols-6">{mobileNav.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => onNavigate(id)} className={cn("flex flex-col items-center gap-1 rounded-xl py-1.5 text-[10px] font-bold", active === id ? "text-[#0f766e]" : "text-[#73827e]")}><Icon className={cn("h-5 w-5", active === id && "fill-[#dcefe9]")} />{label}</button>)}</div></nav><div className="hidden fixed bottom-5 right-5 z-30 gap-2 xl:flex"><button onClick={() => onNavigate("provider")} title="Provider portal" className="grid h-11 w-11 place-items-center rounded-full bg-white text-[#0f766e] shadow-lg"><Building2 className="h-5 w-5" /></button><button onClick={() => onNavigate("movers")} title="Mover portal" className="grid h-11 w-11 place-items-center rounded-full bg-white text-[#b56642] shadow-lg"><Truck className="h-5 w-5" /></button><button onClick={() => onNavigate("admin")} title="Admin portal" className="grid h-11 w-11 place-items-center rounded-full bg-[#123b38] text-white shadow-lg"><ShieldCheck className="h-5 w-5" /></button></div></div>;
}
