// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://coesgsnwfbvuocrylxqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_I_pv0X0SXaw69oXAbJLiYQ_iZw8gkNC";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
